### ISSUE TITLE
Error while running the code

### ISSUE THREAD

**Issue by palangappa** [abrohit/CryptoTrader-Bot#1]
I entered my key and secret, also imported all necessary packages. Still getting this error. Kindly help me

 File "main.py", line 18, in <module>
    key = os.environ['c5c53f3985921f663f7de***********']#Your CoinDcx key.
  File "C:\Python38\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'c5c53f3985921f663f7de0e9*************'

**Comment by abrohit** [comment]
The code:
```
dotenv_file = '.env'
if os.path.isfile(dotenv_file):    
    dotenv.load_dotenv(dotenv_file)
```

Loads a .env file that stores protected data such as passwords, keys, secrets, etc. The function [`os.environ['Key']`](https://github.com/abrohit/CryptoTrader-Bot/blob/main/main.py#L18) accesses the 'Key' from the .env file.

In your case, you can simply remove the [`dotenv_file`](https://github.com/abrohit/CryptoTrader-Bot/blob/main/main.py#L13) part of the code (The code above) and enter your key like,

`key = 'someKey'`
`secret = 'someSecret'`
